[package]
name = "libcruby-sys"
version = "0.5.0"
authors = ["Godhuda <engineering+godhuda@tilde.io>"]
build = "build.rs"
include = [
    "**/*.rs",
    "Cargo.toml",
    "ruby_info.rb",
    "helix-runtime-0-5-0.lib" # Keep in sync with version
]

[dependencies]

libc = "*"
