os:
  - linux
  - osx

dist: trusty # For linux

sudo: false

language: ruby
rvm:
  - 2.4.0

cache:
  directories:
    - $HOME/.rvm/gems
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

env:
  global:
    - EXAMPLES="console membership turbo_blank"
    - VERBOSE=true
    # This isn't expected to pass yet
    #- EXAMPLES="duration"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - export PATH="$HOME/.cargo/bin:$PATH"

install:
  - ./scripts/ci-install

script:
  - ./scripts/ci-test
