[package]
name = "activesupport_duration"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Godfrey Chan <godfreykfc@gmail.com>"]

[lib]
name = "activesupport_duration"
doctest = false
crate-type = ["staticlib"]

[dependencies]
libc = "=0.2.1"
va_list = "0.0.1"

[dependencies.ffi_buf]
version = "1.0.0"
path = "../../../crates/ffi_buf"
