[package]
name = "duration"
version = "0.1.0"
authors = ["Godfrey Chan <godfreykfc@gmail.com>"]

[lib]

crate-type = ["cdylib"]

[dependencies]

libc = "*"
rand = "*"

[dependencies.libcruby-sys]

path = "../../crates/libcruby-sys"

[dependencies.helix]

path = "../.."
